export const AppURL = {
	HOME: '/',
	ACCOUNT: '/account',
	VIEWS_PHONE: '/views/dien-thoai/*-:phoneBranchId',
	VIEWS: '/views/*',
	PROFILE_INFO: '/profile/info',
	PROFILE: '/profile',
	CHECKOUT: '/checkout',
	PROFILE_CHANGEPWD: '/profile/changepwd',
	PRODUCTDETAIL: '/product_detail/*-:idProduct.*',
	NEWSDETAIL: '/news_detail/*-:idNews.*',
	SEARCH: '/search',
	ORDER: '/order/*',
	ORDER_WAITING: '/orderStatus/waiting',
	ORDER_SHIPPING: '/order/shipping',
	ORDER_ALL: '/order/all',
	ORDER_DETAIL: '/order/:id',
	ORDER_PROCESSING: '/order/processing',
	ORDER_COMPLETED: '/order/completed',
	ORDER_CANCELLED: '/order/cancelled',
	ORDER_PENDING: '/order/pending',
	RECOMMEND: '/views/san-pham-goi-y',
	LOGIN: '/admin/login',
};
