export const AppURL = {
	HOME: '/',
	ACCOUNT: '/account',
	VIEWS: '/views/*-:phoneBranchId',
	PROFILE_INFO: '/profile/info',
	PROFILE: '/profile',
	CHECKOUT: '/checkout',
	PROFILE_CHANGEPWD: '/profile/changepwd',
	PRODUCTDETAIL: '/product_detail/*-:idProduct.*',
	NEWSDETAIL: '/news_detail/*-:idNews.*',
	SEARCH: '/search',
	ORDER: '/order/*',
	ORDER_WAITING: '/order/waiting',
	ORDER_SHIPPING: '/order/shipping',
	ORDER_ALL: '/order/all',
	ORDER_DETAIL: '/order/:id',
};
